/* eslint-disable import/prefer-default-export */
export const SYNC_USER_LOCALLY_AND_FIREBASE = 'SYNC_USER_LOCALLY_AND_FIREBASE';
export const SYNC_USER_TO_BACKEND = 'SYNC_USER_TO_BACKEND';
export const GET_ALL_USERS_SHIPPING_ORDERS = 'GET_ALL_USERS_SHIPPING_ORDERS';
export const CREATE_NEW_SHIPPING_ORDERS = 'CREATE_NEW_SHIPPING_ORDERS';
export const SYNC_USER_TO_DATASTORE = 'SYNC_USER_TO_DATASTORE';
